-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 15:34:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pets` (
  `idPets` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `DOB` DATETIME NOT NULL,
  PRIMARY KEY (`idPets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vets` (
  `idVets` INT NOT NULL,
  `VetName` VARCHAR(45) NOT NULL,
  `VetMobile` VARCHAR(45) NOT NULL,
  `VetEmail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owners` (
  `idOwners` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `Number` VARCHAR(10) NOT NULL,
  `Pets_idPets` INT NOT NULL,
  `Vets_idVets` INT NOT NULL,
  PRIMARY KEY (`idOwners`, `Pets_idPets`, `Vets_idVets`),
  INDEX `fk_Owners_Pets_idx` (`Pets_idPets` ASC) VISIBLE,
  INDEX `fk_Owners_Vets1_idx` (`Vets_idVets` ASC) VISIBLE,
  CONSTRAINT `fk_Owners_Pets`
    FOREIGN KEY (`Pets_idPets`)
    REFERENCES `mydb`.`Pets` (`idPets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Owners_Vets1`
    FOREIGN KEY (`Vets_idVets`)
    REFERENCES `mydb`.`Vets` (`idVets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccines` (
  `idVaccines` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Dosage` VARCHAR(45) NOT NULL,
  `Cost` VARCHAR(45) NOT NULL,
  `Vets_idVets` INT NOT NULL,
  `Pets_idPets` INT NOT NULL,
  PRIMARY KEY (`idVaccines`, `Pets_idPets`),
  INDEX `fk_Vaccines_Vets1_idx` (`Vets_idVets` ASC) VISIBLE,
  INDEX `fk_Vaccines_Pets1_idx` (`Pets_idPets` ASC) VISIBLE,
  CONSTRAINT `fk_Vaccines_Vets1`
    FOREIGN KEY (`Vets_idVets`)
    REFERENCES `mydb`.`Vets` (`idVets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaccines_Pets1`
    FOREIGN KEY (`Pets_idPets`)
    REFERENCES `mydb`.`Pets` (`idPets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
